mm2/Little-CMS

src/lcms2_internal.h
This came up during testing of the second Ghostscript 9.16 release candidate, causing a bus error
on SPARC/Solaris with gcc.
At least some configurations of gcc on UltraSPARC require 8 byte alignment of
memory pointers (even on 32 bit user space, where sizeof(void *) == 4).
Rather than contaminate the source, provide ability to set the ptr alignment
on the compiler command line (on Unix, using CFLAGS when calling configure).
=> Allow ptr alignment to be set at build time

src/cmsopt.c
This patch fixes a segmentation fault on Linux and likely other platforms.
For reproduction use:
$ linkicc -o device_link.icc -l \`oyranos-profile --path sRGB.icc\` \`oyranos-profile --path sRGB.icc\`
Discussion:
The crash happens if two identical profiles are linked to a
device link profile and cmsTransform2DeviceLink() obtains the
cmsFLAGS_CLUT_POST_LINEARIZATION or cmsFLAGS_CLUT_PRE_LINEARIZATION
flags as in the above demo. lcms2.h says to the flags:
define cmsFLAGS_CLUT_POST_LINEARIZATION  0x0001    // create postlinearization tables if possible
That means to my understanding, the flags shall perform a reasonable
fallback, in case the linearisation curves are not created. This patch
lets create a device link profile, even without the curves and
avoids a segmentation fault.
=> Fix idendity device link with LINEARIZATION flags

include/lcms2.h
As discussed yesterday, this is what I had in mind, based on your comments:
Firstly, protect the endian decisions in lcms2.h so that settings given on the
compiler command line are not silently overridden. Thus being set explicitly
gets the highest priority.
Secondly, use the endianness detected by the configure script, and remove the
complex and error prone stuff for PPC platforms from lcms2.h. Thus the endianess
from configure gets second highest priority.
Thirdly, if neither of the above are set, fall back to some simple (and long
standing) platform/compiler specific tests. These should rarely, if ever, come
into play in a "normal" build for a "normal" Unix-like system.
=> Simplify/Improve endian decisions in lcms2.h

src/cmssm.c
Currently not using "tc" variable of algorithm by softsurfer.
GCC will report an error.
Commented tc so that it can be utilised in future if needed.
=> Remove tc to fix gcc error.

src/cmslut.c
Memory is allocated for NewElem ->Tab.T but NewElem ->Tab.TFloat is checked for Null.
Corrected mistake in current patch.
=> Null Check mismatch

src/cmsxform.c
This is a regression:
```
$ git bisect log
git bisect start 'master' 'lcms2-2.7'
git bisect bad 288c1505e78ef7d94ecc67729fdca91151f74bac
git bisect good b32dcedd13b3fc2ea7a8099cc0f67eaa31b8c298
git bisect bad adb64b44364e3cd8fabc5a58a0da6841195348ca
git bisect good a7fc6e39ceeeac8bdbd24f08ebb08330d15c5d33
```
It happens when compiling colord git master with Little-CMS git master:
```
($ cd colord && ./autogen.sh && make)
GEN      AdobeRGB1998.icc
=================================================================
==4238==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x7fc76e44dc8c at pc 0x7fc774985435 bp 0x7ffe2a7a8810 sp 0x7ffe2a7a8808
READ of size 4 at 0x7fc76e44dc8c thread T0
0 0x7fc774985434 in UnrollFloatsToFloat /home/lebedevri/src/Little-CMS/src/cmspack.c:1079
1 …
```
=> Fix heap-buffer-overflow in FloatXFORM().

src/cmsplugin.c
Checked if _cmsCreateSubAlloc fails to allocate memory.
=> Fix allocation failure check.

testbed/Makefile.am
When 'make check' is run, ./testcms is run in testbed/Makefile. This uses the default library path, and so will use an existing LCMS 2 installation or fail if LCMS 2 is not already installed. This patch fixes the Makefile so the tests can be run after build, but before install, to test the just-built LCMS 2.
I haven't re-generated the checked-in autotools files as they were built using a different version to the one I have locally and running them generates a raft of spurious changes.
=> Set LD_LIBRARY_PATH in testbed so just-built LCMS is tested

src/lcms2_internal.h
When built with Undefined Behavior Sanitizer, FROM_16_TO_8 raises signed integer overflow errors.
All operands get promoted to integer. Forcing Unsigned arithmetic gets rid of those errors.
=> Update FROM_16_TO_8 macro not to raise UBSan error

src/cmsplugin.c
Function 'va_start' is called at line:485. But, 'va_end' is not called before returning from function '_cmsIOPrintf()' at line:488. 
The va_end performs cleanup for the args object initialized by a call to va_start. If va_end is not called before a function that calls va_start returns, the behavior is undefined.
=> NO_VA_END in cmsplugin.c

src/cmstypes.c
The root array gets filled by strcpy for the count of chars until
zero terminator. The bytes after the string are undefined, but gets
written into the bytestream. Memory debuggers like valgrind complain
about use of uninitialised values. As well a written profile might
contain random bytes, which have to be tracked by the profile ID.
Tools like iccToXml might by affected.
The memset initialises the "root" array, avoids the random values and
fixes the warnings.
=> Fix writing of arbitrary chars into ColorantTable Name

lcms2.pc.in
Needed (sometimes) for static linking (see [1], [2] and [3] for
original buildroot compile problem).
[1] http://autobuild.buildroot.net/results/5ce/5cee20afd8bef5268832cddcb3a5270746be7a57
[2] http://lists.busybox.net/pipermail/buildroot/2016-November/177187.html
[3] http://lists.busybox.net/pipermail/buildroot/2016-November/177188.html
Signed-off-by: Peter Seiderer <ps.report@gmx.net>
=> Fix lcms2.pc.in thread library dependency.

src/cmsps2.c
Return value of a function 'cmsCreateTransformTHR' is dereferenced at cmsps2.c:844 without checking.
So, added check on return value of function 'cmsCreateTransformTHR'.
=> added check on return value of a function

configure.ac, include/lcms2.h, m4/ax_append_compile_flags.m4, m4/ax_append_flag.m4, m4/ax_check_compile_flag.m4, m4/ax_gcc_func_attribute.m4, m4/ax_require_defined.m4, testbed/Makefile.am
These patches hide symbols from _src/lcms2_internal.h_ and _src/cmsalpha.c_ that are not marked for export in the header file.
Files in _m4/_ are from the https://www.gnu.org/software/autoconf-archive/. The actual changes in _configure.ac, include/lcms2.h_ and _testbed/Makefile.am_ are rather small.
Changes have been tested with GCC and Clang.
=> Hide private symbols for autoconf systems

include/lcms2.h
After the latest changes CMSEXPORT and CMSAPI were undefined for Windows static (non-DLL) builds.
=> Fix windows static builds

Projects/VC2012/lcms2_DLL/lcms2_DLL.vcxproj, Projects/VC2012/lcms2_static/lcms2_static.vcxproj, src/lcms2_internal.h
Simple fix adds a file to the project and applies some #defines for older header files. Fixes #126.
=> Fix compilation on older versions of MSVC

src/cmspack.c, src/cmstypes.c, src/cmswtpnt.c
Hi,
Pretty small change I had locally for a long time. Just marks some constant arrays as const letting compiler put them in r/o section. 
Regards,
Kacper
=> Constify some big arrays to allow to compiler put them in read only section.

.travis.yml, configure.ac, include/lcms2.h, m4/ax_append_compile_flags.m4, m4/ax_append_flag.m4, m4/ax_check_compile_flag.m4, m4/ax_gcc_func_attribute.m4, m4/ax_require_defined.m4
As discussed at https://github.com/mm2/Little-CMS/pull/115, hiding non-public symbols should now work on OSX as well. I have extended the test matrix as well. CI results for this branch are at 
https://travis-ci.org/thomas-weber/Little-CMS/builds/290930842
**TODO 1**: after the merge, you need to regenerate the configure script. The Travis build does this for every build, but I thought it would make sense to check that you can generate a correct configure script on your machine.
**TODO 2**: the current .travis.yml flie runs `brew update` for each build due to a bug in the current images which increases the build time for OSX. This should be fixed mid-november, as stated in the file.
=> Enable hidden symbols on osx

src/cmsintrp.c, src/cmsopt.c, src/cmsps2.c, src/cmstypes.c, src/cmswtpnt.c
LittleCMS now compiles without warnings using:
CFLAGS=-Wall ./configure && make
=> Reindent some lines, fixing gcc indentation warnings.

src/cmsopt.c
When the call to CurvesAlloc() fails in OptimizeByJoiningCurves()
the cleanup code will try to free the ObtainedCurves twice. This
is because ObtainedCurves has also been inserted into the
pipeline by the call to cmsPipelineInsertStage().
This commit NULLs the ObtainedCurves variable immediately after
the insertion into the pipeline was succesful and also moves
later use of ObtainedCurves earlier to compensate for setting
ObtainedCurves to NULL. This avoids the double free.
=> Fix double free of curve data structure.

src/cmsps2.c
BuildColorantList() concatenates 32 bit data in each iteration. The max value of iteration can be 16.
Thus buffer overflow can occur with storage of 128 bytes. It would need 512 bytes in worst case.
=> Buffer overflow fix.

src/cmsps2.c
As reported some time ago [1], some PS interpreters have issues with the CSA code lcms2 emits
when gamma tables are encountered in the icc profile. This patch picks up the ideas from the
mentioned mailing list thread and implements them in lcms2.
Testing happened mostly with the icc profiles provided directly in the testbed folder and those generated by the testcms program. The results are all parseable by ghostscript. It should not be left unmentioned that this does **not** cover the modified code path in `EmitCIEBasedDEF`! It would be nice if somebody with an appropriate icc profile could test that one.
Generally it would be nice if we could merge this patch (or some other solution) into lcms2, since this is still a show stopper for a proper adoption of lcms2 in the PS output device of …
=> Cleanup PostScript CSA Generation

src/cmsalpha.c
(This was originally reported in #162.)
Without this fix, FormatterPos() is broken for 16SE requests.  (Note that no case returns `2`, the index into the 16SE row!)
Fix is simple: when 2-bytes are requested, but half-float is not, check endianness.  If T_ENDIAN16, return 16SE; otherwise, return 16.
(Also a minor typo fix on a neighboring comment.)
=> cmsalpha.c : fix broken behavior on 16-bit SE 

Makefile.am, configure.ac, lcms2.pc.in, plugins/Makefile.am, plugins/fast_float/Makefile.am, plugins/fast_float/src/Makefile.am
I've created a pull to incorporate building and installing the fast_float plugin via the autoconf configure.  It implements a ./configure --with-fastfloat parameter, that will allow make and make install to build and install the static liblcms2_fast_float.a and lcms2_fast_float.h in /usr/local/*.  The ./configure --help documents the GPL 3.0 constraint for --with-fastfloat.
I know this is probably a bit of an overreach for an outside developer, but I'm working on incorporating the fast_float plugin in the RawTherapee build process and something like this is the best thing I can conjure to retain a hope that "regular people" will be able to compile RawTherapee with fast_float.  I've tested fast_float with my rawproc software, and it helps me retain LittleCMS for my display transform, which …
=> fast_float autoconf/automake build

COPYING
This word wraps the `COPYING` file at 80 characters to match common conventions for license files. In particular, this allows users to generate better formatted license reports when this package is used down stream.
One such example is when this library is used with the [`Pillow`](https://pypi.org/project/Pillow/) Python package, and an end user uses [`pip-licenses`](https://pypi.org/project/pip-licenses/) to generate a license report.
=> Word wrap license file

configure.ac, src/cmsio0.c
Hello, thanks for maintaining LCMS.
As discussed in https://github.com/mm2/Little-CMS/issues/170, `gmtime` uses internal storage that is static, which means that it's not threadsafe. This PR ensures that threadsafe alternatives of this function are used (if available).
This has been successfully tested on the [JPEG XL test suite](https://github.com/libjxl/libjxl/blob/main/doc/building_and_testing.md) under ThreadSanitizer without requiring a mutex in the top-level APIs (see https://github.com/libjxl/libjxl/issues/53).
Cheers,
Kleis
=> Ensure threadsafe alternative of gmtime is used

configure.ac, src/cmsplugin.c
MinGW-w64 defines `_gmtime64_s` on both i686 and x86_64 targets.
Prefer to use the `gmtime_s` macro to avoid that `_gmtime64_s` is
being called on Windows 32-bit, which will not work.
This PR also generally ensures that a threadsafe alternative
is provided for toolchains targeting Windows i686.
Context: https://github.com/libvips/build-win64-mxe/issues/31.
=> Prefer to use gmtime_s instead

src/cmsio0.c
I have found this issue while working on lcms support in the OpenJDK. One of our testcase rarely crashed when the lcms is used in the very concurrent code, around thousand of threads.
I can reproduce the problem on linux and mac(I think the problem exists on windows as well but I cannot reproduce it even after a few hours of test execution) common crash stack traces are:
```
C [liblcms.so+0x4ac70] _cmsReadTypeBase+0x20
C [liblcms.so+0x253aa] cmsReadTag+0x1ba
C [liblcms.so+0x2629e] ReadICCMatrixRGB2XYZ+0x1e
C [liblcms.so+0x26acc] _cmsReadOutputLUT+0xac
C [liblcms.so+0x125ff] DefaultICCintents+0x39f
C [liblcms.so+0x5fbe3] cmsCreateExtendedTransform+0x2a3
C [liblcms.so+0x6019c] cmsCreateMultiprofileTransformTHR+0xfc
C [liblcms.so+0x6022a] cmsCreateMultiprofileTransform+0x5a 
```
or 
```
C …
```
=> cmsReadTag memory race

plugins/fast_float/src/fast_16_tethra.c, plugins/fast_float/src/fast_8_tethra.c, plugins/fast_float/src/fast_float_curves.c, plugins/fast_float/src/fast_float_tethra.c
It turned out I had missed adjusting the input pointers for the alpha channels in my first attempt to fix it, so it copied the same pixel to the whole output line.
Also, while looking at all the code again to find the issue, I noticed the stride values were missing in FastEvaluateFloatGrayCurves and FastFloatGrayIdentity.
I hope this fixes the alpha issues for real now...
=> Really fix alpha handling in fast float (hopefully...)

plugins/fast_float/src/fast_float_tethra.c
One more alpha channel bug that somehow slipped my testing when preparing PR #271.
A missing type cast caused a blank canvas in Krita when using float color space in combination with a CLUT display profile, so still related to issue #247.
All good things come in threes...
=> Fix copy alpha type mismatch in FloatCLUTEval

plugins/fast_float/src/fast_16_tethra.c, plugins/fast_float/src/fast_8_tethra.c, plugins/fast_float/src/fast_float_cmyk.c, plugins/fast_float/src/fast_float_lab.c, plugins/fast_float/src/fast_float_tethra.c
Turned out I made a mistake with channel index, tethra is always 3 + Alpha as input, so when converting RGB => CMYK it would crash because I used the output Alpha index.
And the Krita unit tests still weren't happy with image bounds on float => float conversions involving Lab or CMYK, so I dug around some more, and found the missing places.
I hope this is now really the last patch required :)
=> Fix float CMYK & Lab copy Alpha, and a previous mistake

src/cmsio0.c
I'd like to silence those two warnings which result from `cmsfilelength` prototype being defined as returning `long int`.
=> Silenced two Int mismatch warnings

plugins/fast_float/testbed/Makefile.am
When building lcms2 out-of-tree with --with-fast-float, "make check" fails because
1. The build files try to link the testbed to the plugin on a path relative to the source directory instead of the build directory;
2. The testbed expects the test?.icc files to be in the same directory.
Fix this by changing it to link relative to the build directory and by copying the test?.icc files to the build directory.
Autoreconf needs to be rerun after this to generate the build files. I thought it better to not send a messy pull request with thousands of lines of generated content.
I'm sorry for the couple of extra whitespace changes in this small file; it seems I need to look at my editor config...
=> Fix out-of-tree build. Requires rerunning autoconf.

src/cmstypes.c
We had an OpenJDK bug report from some one experimenting with the very latest Xcode 13.3 : https://bugs.openjdk.java.net/browse/JDK-8283221
The gist of it is that OpenJDK defaults to warnings as errors and the latest clang reports
cmstypes.c: parameter 'SizeOfTag' set but not used [-Werror,-Wunused-but-set-parameter]
void *Type_ProfileSequenceId_Read(struct _cms_typehandler_struct* self, cmsIOHANDLER* io, cmsUInt32Number* nItems, cmsUInt32Number SizeOfTag)
It corresponds to the case fixed in this PR.
I guess there may once have been a subsequent read that needed this check, or perhaps it is just a pattern to make sure a check is always present in case another read is added.
=> Xcode 13.3 warning on var set but not used in cmstypes.c

configure.ac
Clang 15 makes -Wimplicit-int an error by default.
Before this fix, configure would think SSE2 support is not present when it is:
```
checking whether compiler supports SSE2... no
```
Signed-off-by: Sam James <sam@gentoo.org>
=> configure.ac: fix configure tests broken with Clang 15 (-Wimplicit-int)

.github/workflows/build.yml, plugins/fast_float/include/meson.build, plugins/fast_float/meson.build, plugins/fast_float/src/meson.build, plugins/fast_float/testbed/meson.build, plugins/threaded/include/meson.build, plugins/threaded/meson.build
Hola Marti, this small PR makes the dependency on the `m` library explicit when building via Meson to avoid undefined reference errors during compilation/linking.
It also allows the development headers to be installed, matching the behaviour of the autotools-based build.
Finally it enables the "fastfloat" option in the Meson-based CI job so it matches the behaviour of the existing autotools-based CI job. (I'm unsure if there's a desire to also enable the "threaded" option, but this PR at least makes things consistent.)
=> Ensure plugins can be built and installed with Meson

utils/meson.build
- `jpgicc` depends on optional `libjpeg`
- `tificc` depends on optional `libtiff-4`
=> Meson: skip utils with missing optional dependencies

plugins/fast_float/src/lcms2_fast_float.rc.in, plugins/threaded/src/lcms2_threaded.rc.in, src/lcms2.rc.in
Mingw headers are all lowercase, and can be used for cross compilation from case sensitive file systems.
The official Windows SDK headers aren't self-consistent wrt upper/lower case, so those headers can't be used on case sensitive systems without a layer providing case insensitivity anyway.
This matches other includes of windows.h throughout the codebase.
=> Fix building on case sensitive mingw platforms

src/cmsio0.c, src/lcms2_internal.h
This fixes generated MD5 checksums of existing profiles not matching between Windows and Unix-based systems, by letting existing profiles preserve their CMM, creator, and platform tag values.
See https://invent.kde.org/graphics/krita/-/commit/1191295a4618a93893987497e3c54e6f0c2fd025#note_634123
=> Roundtrip CMM, platform, and creator tags

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml
Set top-level read-only permissions to all workflows; for the jobs that require write-permissions, give them only job-level
Closes #366
=> CI: set minimal permissions to GitHub Workflows

meson.build, meson_options.txt
Add the option to meson to disable the build of utils (when only the library is required to be built.)
=> Allow optional build of utils using meson

plugins/threaded/src/meson.build
Fixes
```
cc  -o plugins/threaded/src/liblcms2_threaded.so plugins/threaded/src/liblcms2_threaded.so.p/threaded_core.c.o plugins/threaded/src/liblcms2_threaded.so.p/threaded_main.c.o plugins/threaded/src/liblcms2_threaded.so.p/threaded_scheduler.c.o plugins/threaded/src/liblcms2_threaded.so.p/threaded_split.c.o -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -shared -fPIC -Wl,--start-group -Wl,-soname,liblcms2_threaded.so -fstack-protector-strong -O2 -pipe -fstack-protector-strong -fno-strict-aliasing '-Wl,-rpath,$ORIGIN/../../../src' -Wl,-rpath-link,/usr/ports/graphics/lcms2/work/lcms2-2.15/_build/src src/liblcms2.so.2.0.15 -Wl,--end-group
ld: error: undefined symbol: pthread_create
```
OS: FreeBSD 13.2-BETA1 (amd64)
=> meson: Link pthread library to threaded plugin

src/cmsplugin.c
No behavior change.
I checked that old and new code has the same results: https://godbolt.org/z/Eo3GT7rzP
=> Simplify fixed-point to double conversion routines

src/cmsnamed.c
Hi, when I test the release version 2.15, I got the error below:
```txt
==12022==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000028 (pc 0x0000006a3e15 bp 0x7ffff47d3380 sp 0x7ffff47d32c0 T0)
==12022==The signal is caused by a READ memory access.
==12022==Hint: address points to the zero page.
#0 0x6a3e15 in cmsFreeProfileSequenceDescription Little-CMS-lcms2.15/src/cmsnamed.c:818:40
#1 0x6a4d99 in cmsDupProfileSequenceDescription Little-CMS-lcms2.15/src/cmsnamed.c:864:5
```
Based on simple analysis, it is because `pseq ->seq` is not checked in cmsFreeProfileSequenceDescription() of version 2.15.
I found that the above problem is fixed in https://github.com/mm2/Little-CMS/commit/ac9e8e16e6f19735b95e6f0e13940256c99aeecd, but the code could still be optimized:
if `pseq ->seq`  is …
=> optimize the code in cmsFreeProfileSequenceDescription()

src/cmserr.c
Hi, when I tested lcms 2.15, I got the error below:
```txt
==25874==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020000fea70 at pc 0x00000066f1d8 bp 0x7ffda729c770 sp 0x7ffda729c768
READ of size 8 at 0x6020000fea70 thread T0
#0 0x66f1d7 in cmsPipelineFree Little-CMS-lcms2.15/src/cmslut.c:1423:22
#1 0x6f7df0 in Type_LUTA2B_Free Little-CMS-lcms2.15/src/cmstypes.c:2856:5
#2 0x657117 in freeOneTag Little-CMS-lcms2.15/src/cmsio0.c:1558:13
#3 0x65390b in cmsCloseProfile Little-CMS-lcms2.15/src/cmsio0.c:1583:9
0x6020000fea71 is located 0 bytes to the right of 1-byte region [0x6020000fea70,0x6020000fea71)
allocated by thread T0 here:
#0 0x52988d in malloc
#1 0x6164c9 in _cmsMallocDefaultFn Little-CMS-lcms2.15/src/cmserr.c:97:20
#2 0x6174f3 in _cmsMalloc …
```
=> Not allow 0 as the size for memory allocation

src/cmsvirt.c
In cmsTransform2DeviceLink(), it does not check if `xform -> Lut` is valid, which can result in potential NULL dereference:
```txt
==27935==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000670a92 bp 0x7fffad69b910 sp 0x7fffad69b900 T0)
==27935==The signal is caused by a READ memory access.
==27935==Hint: address points to the zero page.
#0 0x670a92 in cmsPipelineGetPtrToFirstStage Little-CMS-lcms2.15/src/cmslut.c:1639:18
#1 0x6de22c in cmsTransform2DeviceLink Little-CMS-lcms2.15/src/cmsvirt.c:1079:11
```
The `xform -> Lut` can be NULL as cmsCreateExtendedTransform() will return a fake transform that sets `xform -> Lut` to NULL, when the flag is `cmsFLAGS_NULLTRANSFORM`.
> Note: here I suppose the valid of arguments should be checked by the caller, so I did not …
=> check whether xform->Lut is valid in cmsTransform2DeviceLink

src/cmsnamed.c
Hi, this fix a potential bug to avoid unintentional memmove.
We should regard any BufferSize < sizeof(wchar_t) as invalid, so to ensure the clipped StrLen is fine.
=> make MLUgetWide() avoid unintentional memmove

.github/dependabot.yml
Closes #423
Similarly to discussed in the issue, this PR configures Dependabot to create a single monthly PR with any version updates on your GitHub Actions.
=> feat: configure dependabot to update workflows

.github/workflows/build.yml, meson.build, testbed/meson.build, utils/psicc/psicc.1, utils/transicc/transicc.1
Two commits:
1. Running the tests in the build directory (and copying the necessary profiles there first). This avoids the creation of new.icc in the source directory. 
2. A small fix for the manpages.
=> Keep src tree clean by running tests in the build directory

Projects/VC2019/jpegicc/jpegicc.vcxproj, Projects/VC2019/lcms2_DLL/lcms2_DLL.vcxproj, Projects/VC2019/linkicc/linkicc.vcxproj, Projects/VC2019/psicc/psicc.vcxproj, Projects/VC2019/testbed/testbed.vcxproj, Projects/VC2019/tiffdiff/tiffdiff.vcxproj, Projects/VC2019/tifficc/tifficc.vcxproj, Projects/VC2019/transicc/transicc.vcxproj, Projects/VC2022/jpegicc/jpegicc.vcxproj, Projects/VC2022/lcms2_DLL/lcms2_DLL.vcxproj, Projects/VC2022/linkicc/linkicc.vcxproj, Projects/VC2022/psicc/psicc.vcxproj, Projects/VC2022/testbed/testbed.vcxproj, Projects/VC2022/tiffdiff/tiffdiff.vcxproj, Projects/VC2022/tifficc/tifficc.vcxproj, Projects/VC2022/transicc/transicc.vcxproj
These settings are the same as for other configurations.
=> Windows: set OutDir and IntDir for ARM64 configuration

.github/workflows/build.yml
See https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source
Also bump actions/checkout from 2 to 4 while at it.
=> CI: add macOS arm64 job

src/cmsxform.c
We got a warning while building:
warning C4244: "=": Konvertierung von "double" in "cmsFloat32Number", möglicher Datenverlust
so I added the cast for cmsFloat32Number.
=> Disable warning

plugins/threaded/src/threaded_split.c
:smile: as it says on the tin: 
> fix bug detected at /Wall warning level in MSVC: error C7664: '>': ordered comparison of pointer and integer zero ('_cmsWorkSlice []' and 'int')
=> fix bug detected at /Wall warning level in MSVC: comparison with the wrong variable: the slides[] pointer instead of the `nslices` count.

plugins/fast_float/src/fast_8_curves.c, plugins/fast_float/src/fast_8_matsh.c, plugins/fast_float/src/fast_8_matsh_sse.c, plugins/fast_float/src/fast_8_tethra.c, plugins/fast_float/src/fast_float_15mats.c, plugins/fast_float/src/fast_float_cmyk.c, plugins/fast_float/src/fast_float_curves.c, plugins/fast_float/src/fast_float_lab.c, plugins/fast_float/src/fast_float_matsh.c, plugins/fast_float/src/fast_float_tethra.c
Another bit that showed during 'pedantic warning mode' MSVC build…
This does away with a C type cast which is not required any more as the variable's type matches the function argument / prototype exactly already without it. No functional change, just a bit of cleanup.
--------
🙏 please forgive the shoddy commit message for this one as that's a straight (edited) cherry-pick off another branch of mine, which tracks lcms2mt. It's crud and this PR description is overriding. 🙏
=> code cleanup: C cast not required anymore as `_cmsGetTransformFlags(struct _cmstransform_struct* CMMcargo)` already matches the incoming type.

.github/workflows/build.yml, meson.build, testbed/meson.build
Require Meson &ge; 0.52 for `visibility:hidden`.  Disable unused import of `fs`, which requires Meson &ge; 0.53.  Downgrade Meson in CI to 0.52.
=> Meson version fixes

meson_options.txt, src/meson.build
https://github.com/mm2/Little-CMS/issues/487
After thinking about it, I consider it is better to control behavior via the new option, as android build detection is not always trivial.
=> meson: ability to disable .so.version libraries
