- src/cmstypes.c
The bug can be seen in Argyll's collink tool with version 2.3 profiles
from lcms. collink checks the string length inside the desc tag and compares
with the count field. collink reports then an error and stops. This patch takes
the real text length and puts it into the desc's count field, which makes
collink happy. The formal bug can be seen in Oyranos git too. Checked with
SampleICC which corrects the text count field by converting to XML and
back. Specification ICC.1:2001-04 (v2.4.0) added an example, which
suggests to do padding if any at end of the tag.
Reproduce:
$ collink lcms_profile_with_dmnd_tag_v2.icc second.icm output.icc
The change uses strlen() to obtain the count of chars.
> Fix writing of desc tag for version 2.4 profiles

- utils/psicc/psicc.c
> Add missing allocation failure check.

- ChangeLog
- configure.ac
- include/lcms2.h
- include/lcms2_plugin.h
- src/cmscgats.c
- src/cmscnvrt.c
- src/cmserr.c
- src/cmsgamma.c
- src/cmsgmt.c
- src/cmsintrp.c
- src/cmsio0.c
- src/cmsio1.c
- src/cmsmtrx.c
- src/cmsopt.c
- src/cmspack.c
- src/cmspcs.c
- src/cmsplugin.c
- src/cmsps2.c
- src/cmssm.c
- src/cmstypes.c
- src/cmsxform.c
- src/lcms2_internal.h
- utils/common/vprf.c
- utils/delphi/lcms2dll.pas
Signed-off-by: Stefan Weil <sw@weilnetz.de>
> Fix some typos (found by codespell)

- src/cmstypes.c
- src/cmsxform.c
> Fix memory leaks

- src/cmstypes.c
> Fix use uninitialized value on stack

- src/cmstypes.c
> Fix memory leak in Type_NamedColor_Read

- src/cmsopt.c
> Fix memory leak in OptimizeByResampling

- src/cmstypes.c
> Fix memory leak in ReadSegmentedCurve

- src/cmsopt.c
- src/cmsxform.c
Signed-off-by: Stefan Weil <sw@weilnetz.de>
> Replace non English caché by cache in comments

- src/cmscgats.c
- src/cmstypes.c
- src/cmsvirt.c
- utils/jpgicc/jpgicc.c
- utils/samples/itufax.c
Signed-off-by: Stefan Weil <sw@weilnetz.de>
> Replace non-ASCII characters

- ChangeLog
- config.guess
- include/lcms2.h
- ltmain.sh
- src/cmscgats.c
- src/cmscnvrt.c
- src/cmserr.c
- src/cmsgamma.c
- src/cmsio0.c
- src/cmsopt.c
- src/cmsplugin.c
- src/cmsps2.c
- src/cmstypes.c
- testbed/Makefile.am
- testbed/Makefile.in
- testbed/testcms2.c
- utils/delphi/lcms2dll.pas
- utils/jpgicc/jpgicc.c
- utils/samples/itufax.c
> Misc. typos

- utils/linkicc/Makefile.am
- utils/psicc/Makefile.am
- utils/samples/Makefile.am
- utils/transicc/Makefile.am
Part of https://github.com/mm2/Little-CMS/issues/193
> Fix man page installation for utils

- configure.ac
Part of https://github.com/mm2/Little-CMS/issues/193
> Fix header compilation error on mingw64 and libjpeg-turbo

- testbed/testcms2.c
- testbed/testcms2.h
Part of https://github.com/mm2/Little-CMS/issues/193
> Improve cross-platform testbed build

- configure.ac
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
> configure.ac: fix --without-fastfloat

- configure.ac
for https://github.com/mm2/Little-CMS/issues/265
> add conftest for compiler support for SSE2

- src/cmstypes.c
> Fix Sting typo

- src/cmsplugin.c
* The previous code from c3d7f491e2daebda2413fb3d2935c51df1c50ac7
still contains undefined behavior, since it just creates
temporary pointer variables.
> Perform type punning via union without undefined behavior

- .github/workflows/build.yml
Current: ucrt64 static job takes 10m 17s and
```
Total Download Size:   154.66 MiB
Total Installed Size:  977.88 MiB
```
Proposed is 9m 27s and no additional download
```
Total Installed Size:  653.59 MiB
```
> Simplify MSYS2 CI jobs further

- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
Please consider enabling the [dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates).
> CI: bump actions versions

- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
> ci: set minimal permissions to GitHub Workflows

- meson_options.txt
according to the meson docs boolean values are not quoted..
> meson_options.txt: unquote boolean values

- src/cmsvirt.c
Added a check for NULL to fix #436.
> Possible NPD in cmsCreate_OkLabProfile
